class PromptimusError(Exception): ...


class LLMNotSet(PromptimusError): ...


class EmbedderNotSet(PromptimusError): ...


class VectorStoreNotSet(PromptimusError): ...


class ParamNotSet(PromptimusError): ...


class FailedToParseOutput(PromptimusError): ...


class MaxIterExceeded(PromptimusError): ...


class InvalidToolName(PromptimusError): ...


class ProviderRetryExceded(PromptimusError): ...


class RecursiveModule(PromptimusError): ...


class InvalidToolConfig(PromptimusError):
    """Raised when a tool is configured with incompatible parameters."""

    ...
